# name: Build & Deploy - KitchenService.Worker

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     env:
#       IMAGE_NAME: kitchenservice-worker
#       IMAGE_TAG: latest
#       REGISTRY: docker.io/your-dockerhub-username  # Substitua pelo seu usuário do Docker Hub

#     steps:
#       - name: Checkout do código
#         uses: actions/checkout@v3

#       - name: Setup .NET
#         uses: actions/setup-dotnet@v3
#         with:
#           dotnet-version: '8.0.x'

#       - name: Testes
#         run: dotnet test KitchenService.sln

#       - name: Setup Docker
#         uses: docker/setup-buildx-action@v3

#       - name: Login no Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build e Push da imagem
#         run: |
#           docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG -f KitchenService.Worker/Dockerfile .
#           docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
