name: 🔍 Testes Unitários - KitchenService

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore KitchenService.sln

      - name: Build
        run: dotnet build KitchenService.sln --configuration Release --no-restore

      - name: Rodar testes
        run: dotnet test KitchenService.sln --configuration Release --no-build --verbosity normal
